import { SkillCategory } from "@prisma/client";

// The Skill master seed list — extracted from seed.ts so it can also be
// imported by prisma/migrate-candidate-skills.ts and any other one-off
// script that needs to seed/reference the same curated list without
// re-running the full seed (which would collide with existing Users/Jobs).
export const skillsData: { name: string; category: SkillCategory; description?: string }[] = [
  // TECHNICAL — Programming Languages
  { name: "JavaScript", category: SkillCategory.TECHNICAL },
  { name: "TypeScript", category: SkillCategory.TECHNICAL },
  { name: "Python", category: SkillCategory.TECHNICAL },
  { name: "Java", category: SkillCategory.TECHNICAL },
  { name: "Go", category: SkillCategory.TECHNICAL },
  { name: "Rust", category: SkillCategory.TECHNICAL },
  { name: "C++", category: SkillCategory.TECHNICAL },
  { name: "C#", category: SkillCategory.TECHNICAL },
  { name: "Ruby", category: SkillCategory.TECHNICAL },
  { name: "PHP", category: SkillCategory.TECHNICAL },
  { name: "Swift", category: SkillCategory.TECHNICAL },
  { name: "Kotlin", category: SkillCategory.TECHNICAL },
  // TECHNICAL — Frontend
  { name: "React", category: SkillCategory.TECHNICAL },
  { name: "Redux", category: SkillCategory.TECHNICAL },
  { name: "Vue.js", category: SkillCategory.TECHNICAL },
  { name: "Angular", category: SkillCategory.TECHNICAL },
  { name: "Next.js", category: SkillCategory.TECHNICAL },
  { name: "Tailwind CSS", category: SkillCategory.TECHNICAL },
  { name: "HTML/CSS", category: SkillCategory.TECHNICAL },
  { name: "React Native", category: SkillCategory.TECHNICAL },
  { name: "Flutter", category: SkillCategory.TECHNICAL },
  // TECHNICAL — Backend
  { name: "Node.js", category: SkillCategory.TECHNICAL },
  { name: "Express.js", category: SkillCategory.TECHNICAL },
  { name: "Django", category: SkillCategory.TECHNICAL },
  { name: "FastAPI", category: SkillCategory.TECHNICAL },
  { name: "Spring Boot", category: SkillCategory.TECHNICAL },
  { name: "GraphQL", category: SkillCategory.TECHNICAL },
  { name: "REST API Design", category: SkillCategory.TECHNICAL },
  { name: "gRPC", category: SkillCategory.TECHNICAL },
  // TECHNICAL — Database
  { name: "PostgreSQL", category: SkillCategory.TECHNICAL },
  { name: "MySQL", category: SkillCategory.TECHNICAL },
  { name: "MongoDB", category: SkillCategory.TECHNICAL },
  { name: "Redis", category: SkillCategory.TECHNICAL },
  { name: "Elasticsearch", category: SkillCategory.TECHNICAL },
  { name: "SQL", category: SkillCategory.TECHNICAL },
  // TECHNICAL — DevOps / Cloud
  { name: "AWS", category: SkillCategory.TECHNICAL },
  { name: "GCP", category: SkillCategory.TECHNICAL },
  { name: "Azure", category: SkillCategory.TECHNICAL },
  { name: "Docker", category: SkillCategory.TECHNICAL },
  { name: "Kubernetes", category: SkillCategory.TECHNICAL },
  { name: "Terraform", category: SkillCategory.TECHNICAL },
  { name: "CI/CD", category: SkillCategory.TECHNICAL },
  { name: "Linux", category: SkillCategory.TECHNICAL },
  { name: "Git", category: SkillCategory.TECHNICAL },
  // TECHNICAL — QA / Testing
  { name: "Selenium", category: SkillCategory.TECHNICAL },
  { name: "Cypress", category: SkillCategory.TECHNICAL },
  { name: "Jest", category: SkillCategory.TECHNICAL },
  { name: "Playwright", category: SkillCategory.TECHNICAL },
  { name: "JUnit", category: SkillCategory.TECHNICAL },
  { name: "Postman", category: SkillCategory.TECHNICAL },
  { name: "Test Automation", category: SkillCategory.TECHNICAL },
  { name: "Performance Testing", category: SkillCategory.TECHNICAL },
  // TECHNICAL — Architecture & Systems
  { name: "System Design", category: SkillCategory.TECHNICAL },
  { name: "Microservices", category: SkillCategory.TECHNICAL },
  { name: "Event-Driven Architecture", category: SkillCategory.TECHNICAL },
  { name: "Distributed Systems", category: SkillCategory.TECHNICAL },
  { name: "Message Queues (Kafka/RabbitMQ)", category: SkillCategory.TECHNICAL },
  // TECHNICAL — Data & AI
  { name: "Machine Learning", category: SkillCategory.TECHNICAL },
  { name: "TensorFlow", category: SkillCategory.TECHNICAL },
  { name: "PyTorch", category: SkillCategory.TECHNICAL },
  { name: "Data Analysis", category: SkillCategory.TECHNICAL },
  { name: "Power BI", category: SkillCategory.TECHNICAL },
  { name: "Tableau", category: SkillCategory.TECHNICAL },
  { name: "Apache Spark", category: SkillCategory.TECHNICAL },
  // TECHNICAL — Design
  { name: "Figma", category: SkillCategory.TECHNICAL },
  { name: "Sketch", category: SkillCategory.TECHNICAL },
  { name: "Adobe XD", category: SkillCategory.TECHNICAL },
  // TECHNICAL — Security
  { name: "Application Security", category: SkillCategory.TECHNICAL },
  { name: "Penetration Testing", category: SkillCategory.TECHNICAL },
  { name: "OAuth / OIDC", category: SkillCategory.TECHNICAL },
  // HUMAN
  { name: "Communication", category: SkillCategory.HUMAN },
  { name: "Problem Solving", category: SkillCategory.HUMAN },
  { name: "Teamwork", category: SkillCategory.HUMAN },
  { name: "Adaptability", category: SkillCategory.HUMAN },
  { name: "Time Management", category: SkillCategory.HUMAN },
  { name: "Critical Thinking", category: SkillCategory.HUMAN },
  { name: "Emotional Intelligence", category: SkillCategory.HUMAN },
  { name: "Leadership", category: SkillCategory.HUMAN },
  { name: "Conflict Resolution", category: SkillCategory.HUMAN },
  { name: "Negotiation", category: SkillCategory.HUMAN },
  { name: "Presentation Skills", category: SkillCategory.HUMAN },
  { name: "Active Listening", category: SkillCategory.HUMAN },
  { name: "Mentoring", category: SkillCategory.HUMAN },
  { name: "Attention to Detail", category: SkillCategory.HUMAN },
  { name: "Decision Making", category: SkillCategory.HUMAN },
  { name: "Creativity", category: SkillCategory.HUMAN },
  // MANAGEMENT
  { name: "Project Management", category: SkillCategory.MANAGEMENT },
  { name: "Agile / Scrum", category: SkillCategory.MANAGEMENT },
  { name: "Stakeholder Management", category: SkillCategory.MANAGEMENT },
  { name: "Strategic Planning", category: SkillCategory.MANAGEMENT },
  { name: "Budgeting", category: SkillCategory.MANAGEMENT },
  { name: "Hiring & Talent Acquisition", category: SkillCategory.MANAGEMENT },
  { name: "Performance Management", category: SkillCategory.MANAGEMENT },
  { name: "OKR Setting", category: SkillCategory.MANAGEMENT },
  { name: "Risk Management", category: SkillCategory.MANAGEMENT },
  { name: "Change Management", category: SkillCategory.MANAGEMENT },
  { name: "Cross-Functional Leadership", category: SkillCategory.MANAGEMENT },
  { name: "Vendor Management", category: SkillCategory.MANAGEMENT },
  // DOMAIN
  { name: "FinTech", category: SkillCategory.DOMAIN },
  { name: "HealthTech", category: SkillCategory.DOMAIN },
  { name: "EdTech", category: SkillCategory.DOMAIN },
  { name: "SaaS", category: SkillCategory.DOMAIN },
  { name: "E-Commerce", category: SkillCategory.DOMAIN },
  { name: "Digital Marketing", category: SkillCategory.DOMAIN },
  { name: "SEO / SEM", category: SkillCategory.DOMAIN },
  { name: "Product Management", category: SkillCategory.DOMAIN },
  { name: "UX Research", category: SkillCategory.DOMAIN },
  { name: "Business Analysis", category: SkillCategory.DOMAIN },
  { name: "Compliance", category: SkillCategory.DOMAIN },
  { name: "Legal", category: SkillCategory.DOMAIN },
  { name: "Accounting", category: SkillCategory.DOMAIN },
  { name: "Supply Chain", category: SkillCategory.DOMAIN },
  { name: "Customer Success", category: SkillCategory.DOMAIN },
];
